# Generated by Django 3.1.5 on 2021-01-20 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Available',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Cerrajero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceType', models.CharField(max_length=100)),
                ('serviceObject', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10, null=True)),
                ('available', models.ManyToManyField(to='main.Available')),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField()),
                ('cerrajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cerrajero')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=50)),
                ('service_object', models.CharField(max_length=50)),
                ('take_piece', models.BooleanField(default=False)),
                ('car_model', models.CharField(blank=True, max_length=30)),
                ('car_year', models.CharField(blank=True, max_length=30)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Waiting', 'Waiting'), ('Accepted', 'Accepted'), ('Canceled', 'Canceled')], default='Waiting', max_length=8)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('cerrajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cerrajero')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cerrajero',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.ciudad'),
        ),
        migrations.AddField(
            model_name='cerrajero',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
